* [2016-01-29 Fri]
** Characteristic Scales
*** Definition
Non-zero constants $t_c$, $y_c$ are called characteristic scales for a function
$y=f(t)$ if the following is true:

1.
  - $[t_c] = [t]$
  - $[y_c] = [t]$

2. Main features of $y=f(t)$ graph are clearly visible in a $mt_c \times ny_c$
   window for moderate values of $m,n$ ($1\lem,n\le10$).

*** Examples
**** 1

$y=A\sin(\pi t/b), t \ge 0$, $A$, $b$ constants, $A = 1 \text{ meter}$, $b=1
\text{ second}$. Reference fig. 1.1.

Characteristic scales are $t_c=b, y_c=A$ since $2b \times 2A$ window captures
main features of graph.

Can understand the features of the graph within this window. Reference fig. 1.2.

Windows of significantly different sizes would give poor representations of
functions. Reference fig. 1.3.

**** 2

$$y = Ae^{-t/b}, t\ge0$$ where $[y]=L$, $[t] = T$, $A$, $b$ constants.

Reference fig. 1.4. Characteristic scales are $t_c=b$, $y_c=A$ since window
$10b \times A$ captures main features.

**** 3

Fig. 1.5 has two sets of characteristic scales; two window sizes are needed to
represent the features, as shown in figs. 1.6 and 1.7.

*** Procedure
Given some (potentially indirect) definition of a graph, how do we indentify the
scales?

If $y=f(t)$ is defined by an equation involving constants $g_1, \ldots, g_m$,
then characteristic scales $t_c$, $y_c$ can be found by solving:

#+begin_src latex
  \begin{equation}
    \begin{aligned}
      t_c &= g_1^{\alpha_1}, \ldots, g_m^{\alpha_m} \\
      y_c &= g_1^{\beta_1}, \ldots, g_m^{\beta_m}
    \end{aligned}
  \end{equation}
#+end_src

for $\alpha_1, \ldots, \alpha_m$ and $\beta_1, \ldots, \beta_m$.

*** Examples
**** 1

Find characteristic scales $t_c$, $y_c$ for $y=f(t)$ defined by

#+begin_src latex
  \left{
  \begin{equation}
    \begin{aligned}
      \frac{dy}{dt} &= \eta\y, \quad t\ge0 \\
      y_{(0)} = \lambda \\
    \end{aligned}
  \end{equation}
#+end_src

$[y]=\Eta, [t]=T$.

Dimensions of $\eta$, $\lambda$:

#+begin_src latex
  \begin{equation}
    \begin{aligned}
      \frac{\Eta}{T} &= [\eta]\Eta \rightarrow [\eta]=\frac{1}{T} \\
      \Eta &= [\lambda]
    \end{aligned}
  \end{equation}
#+end_src

Scales for $t$, $y$:

#+begin_src latex
  \begin{equation}
    \begin{aligned}
      t_c &= \eta^{\alpha_1} \lambda^{\alpha_2} \\
      \implies T &= T^{-\alpha_1}\Eta^{\alpha_2} \\
      \implies \alpha_1=-1,\quad \alpha_2 = 0 \\
      \implies t_c = \frac{1}{\eta}
    \end{aligned}
  \end{equation}
#+end_src

#+begin_src latex
  \begin{equation}
    \begin{aligned}
      y_c &= \eta^{\beta_1} \lambda^{\beta_2} \\
      \implies \Eta &= T^{-\beta_1}\Eta^{\beta_2} \\
      \implies \beta_1=0,\quad \beta_2 = 1 \\
      \implies y_c = \lambda
    \end{aligned}
  \end{equation}
#+end_src

**** 2

Do the same for
#+begin_src latex
  \left{
  \begin{equation}
    \begin{aligned}
      \frac{d^2y}{dt^2} &= \eta \frac{dy}{dt} + \mu y^2,\quad t \ge 0 \\
      y_{(0)}=\lambda, \quad \frac{dy}{dt}(0) = 0
    \end{aligned}
  \end{equation}
#+end_src

$[y]=L$, $[t]=T$, $\eta$, $\mu$, $\lambda$ constants.

Dimensions of $\eta$, $\mu$, $\lambda$:
#+begin_src latex
  \begin{equation}
    \begin{aligned}
      [\lambda] &= L \\
      [\eta]\frac{L}{T} &= \frac{L}{T^2} \rightarrow [\eta] &= \frac{1}{T} \\
      [\mu]L^2 &= \frac{L}{T^2} \rightarrow [\mu] &= \frac{1}{LT^2} \\
    \end{aligned}
  \end{equation}
#+end_src

Scale for $t$:
#+begin_src latex
  \begin{equation}
    \begin{aligned}
      t_c &= \eta^{\alpha_1}\mu^{\alpha_2}\lambda^{\alpha_3} \\
      &= T^{-\alpha_1}(L^{-1}T^{-2})^{\alpha_2}L^{\alpha_3} \\
      \implies L^0T^1 &= L^{-\alpha_2+\alpha_3}T^{\alpha_1-2\alpha_2} \\
    \end{aligned}
  \end{equation}

  \begin{equation}
    \begin{pmatrix}
      -1 & -2 & 0 \\
      0 & -1 & 1 \\
    \end{pmatrix}
  \begin{pmatrix}
    \alpha_1 \\
    \alpha_2 \\
    \alpha_3 \\
  \end{pmatrix}
  =
  \begin{pmatrix}
    1\\0
  \end{pmatrix}
  \end{equation}

  Where $\alpha_3$ is free.

  \begin{equation}
    \begin{aligned}
      -\alpha_1-2\alpha_2 &= 1 \rightarrow \alpha_1=-2\alpha_2-1=-2\alpha_3-1\\
      -\alpha_2 + \alpha_3 = 0 \rightarrow \alpha_2&=\alpha_3
    \end{aligned}
  \end{equation}

  \begin{equation}
    \begin{pmatrix}
      \alpha_1 \\ \alpha_2 \\\alpha_3 \\
    \end{pmatrix}
    =
    \begin{pmatrix}
      -2\alpha_3-1 \\ \alpha_3 \\\alpha_3 \\
    \end{pmatrix}
    = \alpha_3
    \begin{pmatrix}
      -2 \\ 1 \\ 1
    \end{pmatrix}
    +
    \begin{pmatrix}
      -1 \\ 0 \\ 0
    \end{pmatrix}
  \end{equation}
#+end_src

Where $\alpha_3$ is free. $\alpha_3=0, \quad \alpha_3\ne0$ gives two scales for
t_c:

#+begin_src latex
  \begin{equation}
    \alpha_3=0 \quad
    \begin{pmatrix}
      -1 \\ 0 \\ 0
    \end{pmatrix}
  \end{equation}

  \begin{equation}
    \implies t_c = \frac{1}{\eta}.
  \end{equation}

  And

  \begin{equation}
    \alpha_3 = \frac{-1}{2} \quad
    \begin{pmatrix}
      \alpha_1 \\ \alpha_2 \\ \alpha_3 \\
    \end{pmatrix}
    =
    \begin{pmatrix}
      0 \\ -1/2 \\ -1/2
    \end{pmatrix}
  \end{equation}

  \begin{equation}
    \implies t_c = \frac{1}{\sqrt{\mu\lambda}}
  \end{equation}
#+end_src

Same for $y_c$

#+begin_src latex
  \begin{equation}
    \begin{aligned}
      y_c &= \frac{\eta^2}{\mu} \\
      y_c &= \lambda
    \end{aligned}
  \end{equation}
#+end_src
